### ISSUE TITLE
What does the parameter 'cluster_type' refer to?

### ISSUE THREAD

**Issue by zhao98** [Bmax-Tech/K-Means-Clustering#1]
Hi, I am reading your work of the implementation for k-means clustering. But I am confused about the parameter in the method 'cluster_results(cluster_type)' in the file 'algorithm.py'. What does this parameter refer to? Could you help me with this?

**Comment by Bmax-Tech** [comment]
Hi @zhao98 
the "cluster_type" parameter value comes from the UI, Pls refer this,
[https://github.com/Bmax-Tech/K-Means-Clustering-UI/blob/c1fc44b18cec726df1fdbf34a1950e4d3ddae459/public/views/home/home.js#L138](url)
that is used to dynamically change the number of clusters depending on the user's preference.

**Comment by zhao98** [comment]
Thank you!
